apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: wrapmaster
  name: deliveryelf
  namespace: northpole
  labels:
    app: deliveryelf
    exposed: "true"
    app.kubernetes.io/part-of: northpole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveryelf
  template:
    metadata:
      labels:
        app: deliveryelf
    spec:
      containers:
        - image: quay.io/ralvares/santa:deliveryelf
          command: ["/bin/entrypoint"]
          args:
            [
              "-listen",
              ":8080",
              "-connect",
              "$(WRAPMASTER_ADDR):$(WRAPMASTER_PORT)",
            ]
          imagePullPolicy: Always
          name: deliveryelf
          envFrom:
            - configMapRef:
                name: deliveryelf-endpoint-config
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deliveryelf
  name: deliveryelf-service
  namespace: northpole
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: deliveryelf
  type: ClusterIP
