# Deployment named "wrapmaster"
# Listens on :8080
# Has SSH keys mounted
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrapmaster
  namespace: northpole
  labels:
    app: wrapmaster
    exposed: "true"
    app.kubernetes.io/part-of: northpole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrapmaster
  template:
    metadata:
      labels:
        app: wrapmaster
    spec:
      containers:
        - image: quay.io/ralvares/santa:wrapmaster
          command: ["/bin/entrypoint"]
          args:
            [
              "-listen",
              ":8080",
            ]
          imagePullPolicy: Always
          name: wrapmaster
          ports:
            - containerPort: 8080
              protocol: TCP
---
# Service named "wrapmaster-service"
# Listens on :8080
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wrapmaster
  name: wrapmaster-service
  namespace: northpole
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: wrapmaster
  type: ClusterIP
