apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s2i-build-and-deploy
  namespace: northpole-pipelines
spec:
  params:
    - default: 'ttl.sh/giftrack:1h'
      name: IMAGE_NAME
      type: string
    - default: 'http://gogs.gogs.svc.cluster.local:3000/developer/santa.git'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: SKIP_PUSH
          value: ''
        - name: PATH_CONTEXT
          value: src/gifttrack
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: workspace
    - name: rhacs-image-scan
      params:
        - name: rox_central_endpoint
          value: roxsecrets
        - name: rox_api_token
          value: roxsecrets
        - name: rox_image
          value: 'quay.io/stackrox-io/roxctl:3.71.0'
        - name: image
          value: $(params.IMAGE_NAME)
        - name: output_format
          value: table
        - name: insecure-skip-tls-verify
          value: 'true'
      runAfter:
        - build
      taskRef:
        kind: Task
        name: rhacs-image-scan
    - name: rhacs-image-check
      params:
        - name: rox_central_endpoint
          value: roxsecrets
        - name: rox_api_token
          value: roxsecrets
        - name: rox_image
          value: 'quay.io/stackrox-io/roxctl:3.71.0'
        - name: image
          value: $(params.IMAGE_NAME)
        - name: output_format
          value: table
        - name: insecure-skip-tls-verify
          value: 'true'
      runAfter:
        - rhacs-image-scan
      taskRef:
        kind: Task
        name: rhacs-image-check
  workspaces:
    - name: workspace