apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/displayName: Generate network policies from a deployment baseline with StackRox/RHACS
    tekton.dev/platforms: linux/amd64
    tekton.dev/tags: security
  labels:
    app.kubernetes.io/version: "0.1"
  name: stackrox-deployment-netpol-baseline
spec:
  description: "Generate network policies from a deployment baseline with StackRox/RHACS"
  params:
  - description: |
      Secret containing the address:port tuple for StackRox Central)
      (example - rox.stackrox.io:443)
    name: rox_central_endpoint
    type: string
  - description: Secret containing the StackRox API token with CI permissions
    name: rox_api_token
    type: string
  - description: The cluster you want to use to get the network baseline
    name: cluster
    type: string
  - description: |
      The directory under 'source' workspace to write connectivity report file
          into.
    name: netpol-path
    type: string
  - default: "false"
    description: |
      When set to `"true"`, skip verifying the TLS certs of the Central
      endpoint.  Defaults to `"false"`.
    name: insecure-skip-tls-verify
    type: string
  steps:
  - env:
    - name: CLUSTER
      value: $(params.cluster)
    - name: ROX_API_TOKEN
      valueFrom:
        secretKeyRef:
          key: rox_api_token
          name: $(params.rox_api_token)
    - name: ROX_ENDPOINT
      valueFrom:
        secretKeyRef:
          key: rox_central_endpoint
          name: $(params.rox_central_endpoint)
    image: quay.io/ralvares/npguard
    name: rox-deployment-netpol-baseline
    resources: {}
    script: >
        #!/usr/bin/env bash

        set +x

        kustomize build $(params.netpol-path) > /tmp/all.yaml

        get_netpol.py && cat networkpolicies.yaml && cp networkpolicies.yaml
        $(params.netpol-path) && cd $(params.netpol-path); kustomize edit add resource
        networkpolicies.yaml
    workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
