apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/categories: Security
    tekton.dev/displayName: Generate Network Policies using StackRox/RHACS
    tekton.dev/platforms: linux/amd64
    tekton.dev/tags: security
  name: stackrox-generate-netpol
  namespace: northpole-pipelines
spec:
  description: Generate Network Policies using roxctl.
  params:
  - description: |
      The directory under 'source' workspace to write connectivity report file
          into.
    name: netpol-path
    type: string
  - description: |
      Enable DNS Rules for Openshift - Port 5353.
    name: openshift
    type: string
  steps:
  - env:
    - name: PARAMS_OUTPUT_DIR
      value: $(params.netpol-path)
    image: quay.io/ralvares/npguard
    name: rox-generate-netpol
    resources: {}
    script: |
      #!/usr/bin/env bash
      kustomize build $(params.netpol-path) > /tmp/all.yaml
      /bin/roxctl generate netpol /tmp/all.yaml > $(params.netpol-path)/netpols.yaml 2> /dev/null && if [ "$(params.openshift)" = "true" ]; then sed -i 's/port: 53/port: 5353/' $(params.netpol-path)/netpols.yaml; fi && cd $(params.netpol-path); kustomize edit add resource netpols.yaml; cat netpols.yaml
    workingDir: $(workspaces.source.path)
  workspaces:
  - name: source
