name: Vulnerability Audit

on:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner with fs command
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: json
          output: trivy-results.json

      - name: Download Vulnerawise
        run: |
          curl -L -o vulnerawise https://github.com/vulnerawise/vulnerawise/releases/download/v0.1/vulnerawise-linux-amd64
          chmod +x vulnerawise

      - name: Update Vulnerawise Database
        run: ./vulnerawise updatedb

      - name: Run Vulnerawise Audit and Generate SARIF Report
        run: |
          ./vulnerawise audit trivy-results.json -o report.sarif > /dev/null | echo

      - name: Upload Vulnerawise SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif

      - name: Enforce Vulnerawise Audit Check
        run: |
          ./vulnerawise audit trivy-results.json
